### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by hmankodiya** [robertklee/KITTI-RoadSeg#7]
How to predict on the road image data using your model from model.py using this weights "_weights_epoch20_val_loss_-1.9479_train_loss_-1.9623.hdf5" available in your one drive link?

Also, are these weights fully trained on the KITTI dataset?

**Comment by robertklee** [comment]
Yes those weights are trained. Please follow the readme for instructions on how to clone the repository. The script will automatically download the required model architecture files and pre-trained weights.

**Comment by hmankodiya** [comment]
Thank you.

**Comment by robertklee** [comment]
just download the weights and put them in the right folder. :)
